# Docker-compose.yml for leed backups
# Must be run by backup-leeds.sh
#
backup:
  image: debian:jessie
  volumes:
    - "$leed_backupdir:/backup"
  volumes_from:
    - "$leed_container"
  command: cp -frpv /var/www/html/ /backup/
